### ISSUE TITLE
Ik snap deze issue zelf niet helemaal

### ISSUE THREAD

**Issue by Amber-vdr** [r20222/look-and-feel-corporate-identity#5]
Maar het blijkt dat de a href niet de child mag zijn van een ul. Zie hieronder voorbeeld:
![image](https://user-images.githubusercontent.com/112861033/204240072-a9452798-8abf-44db-ab37-aa8151873918.png)

**Comment by r20222** [comment]
Ik heb het opgelost door de `<a href="agenda">` te verwijderen en een `<button>` toe te voegen binnen de `<li>`. 🥇
